/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HarvesterhciIoV1beta1VirtualMachineBackupList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HarvesterhciIoV1beta1VirtualMachineBackupList{}

// HarvesterhciIoV1beta1VirtualMachineBackupList VirtualMachineBackupList is a list of VirtualMachineBackup resources
type HarvesterhciIoV1beta1VirtualMachineBackupList struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`
	Items []HarvesterhciIoV1beta1VirtualMachineBackup `json:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`
	Metadata K8sIoV1ListMeta `json:"metadata"`
}

type _HarvesterhciIoV1beta1VirtualMachineBackupList HarvesterhciIoV1beta1VirtualMachineBackupList

// NewHarvesterhciIoV1beta1VirtualMachineBackupList instantiates a new HarvesterhciIoV1beta1VirtualMachineBackupList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHarvesterhciIoV1beta1VirtualMachineBackupList(items []HarvesterhciIoV1beta1VirtualMachineBackup, metadata K8sIoV1ListMeta) *HarvesterhciIoV1beta1VirtualMachineBackupList {
	this := HarvesterhciIoV1beta1VirtualMachineBackupList{}
	this.Items = items
	this.Metadata = metadata
	return &this
}

// NewHarvesterhciIoV1beta1VirtualMachineBackupListWithDefaults instantiates a new HarvesterhciIoV1beta1VirtualMachineBackupList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHarvesterhciIoV1beta1VirtualMachineBackupListWithDefaults() *HarvesterhciIoV1beta1VirtualMachineBackupList {
	this := HarvesterhciIoV1beta1VirtualMachineBackupList{}
	var metadata K8sIoV1ListMeta
	this.Metadata = metadata
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetItems returns the Items field value
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetItems() []HarvesterhciIoV1beta1VirtualMachineBackup {
	if o == nil {
		var ret []HarvesterhciIoV1beta1VirtualMachineBackup
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetItemsOk() ([]HarvesterhciIoV1beta1VirtualMachineBackup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) SetItems(v []HarvesterhciIoV1beta1VirtualMachineBackup) {
	o.Items = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetMetadata() K8sIoV1ListMeta {
	if o == nil {
		var ret K8sIoV1ListMeta
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) GetMetadataOk() (*K8sIoV1ListMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) SetMetadata(v K8sIoV1ListMeta) {
	o.Metadata = v
}

func (o HarvesterhciIoV1beta1VirtualMachineBackupList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HarvesterhciIoV1beta1VirtualMachineBackupList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	toSerialize["items"] = o.Items
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *HarvesterhciIoV1beta1VirtualMachineBackupList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHarvesterhciIoV1beta1VirtualMachineBackupList := _HarvesterhciIoV1beta1VirtualMachineBackupList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHarvesterhciIoV1beta1VirtualMachineBackupList)

	if err != nil {
		return err
	}

	*o = HarvesterhciIoV1beta1VirtualMachineBackupList(varHarvesterhciIoV1beta1VirtualMachineBackupList)

	return err
}

type NullableHarvesterhciIoV1beta1VirtualMachineBackupList struct {
	value *HarvesterhciIoV1beta1VirtualMachineBackupList
	isSet bool
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineBackupList) Get() *HarvesterhciIoV1beta1VirtualMachineBackupList {
	return v.value
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineBackupList) Set(val *HarvesterhciIoV1beta1VirtualMachineBackupList) {
	v.value = val
	v.isSet = true
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineBackupList) IsSet() bool {
	return v.isSet
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineBackupList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHarvesterhciIoV1beta1VirtualMachineBackupList(val *HarvesterhciIoV1beta1VirtualMachineBackupList) *NullableHarvesterhciIoV1beta1VirtualMachineBackupList {
	return &NullableHarvesterhciIoV1beta1VirtualMachineBackupList{value: val, isSet: true}
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineBackupList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineBackupList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


