/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1FeatureKVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1FeatureKVM{}

// KubevirtIoApiCoreV1FeatureKVM struct for KubevirtIoApiCoreV1FeatureKVM
type KubevirtIoApiCoreV1FeatureKVM struct {
	Hidden *bool `json:"hidden,omitempty"`
}

// NewKubevirtIoApiCoreV1FeatureKVM instantiates a new KubevirtIoApiCoreV1FeatureKVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1FeatureKVM() *KubevirtIoApiCoreV1FeatureKVM {
	this := KubevirtIoApiCoreV1FeatureKVM{}
	return &this
}

// NewKubevirtIoApiCoreV1FeatureKVMWithDefaults instantiates a new KubevirtIoApiCoreV1FeatureKVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1FeatureKVMWithDefaults() *KubevirtIoApiCoreV1FeatureKVM {
	this := KubevirtIoApiCoreV1FeatureKVM{}
	return &this
}

// GetHidden returns the Hidden field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1FeatureKVM) GetHidden() bool {
	if o == nil || IsNil(o.Hidden) {
		var ret bool
		return ret
	}
	return *o.Hidden
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1FeatureKVM) GetHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.Hidden) {
		return nil, false
	}
	return o.Hidden, true
}

// HasHidden returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1FeatureKVM) HasHidden() bool {
	if o != nil && !IsNil(o.Hidden) {
		return true
	}

	return false
}

// SetHidden gets a reference to the given bool and assigns it to the Hidden field.
func (o *KubevirtIoApiCoreV1FeatureKVM) SetHidden(v bool) {
	o.Hidden = &v
}

func (o KubevirtIoApiCoreV1FeatureKVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1FeatureKVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hidden) {
		toSerialize["hidden"] = o.Hidden
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1FeatureKVM struct {
	value *KubevirtIoApiCoreV1FeatureKVM
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1FeatureKVM) Get() *KubevirtIoApiCoreV1FeatureKVM {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1FeatureKVM) Set(val *KubevirtIoApiCoreV1FeatureKVM) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1FeatureKVM) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1FeatureKVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1FeatureKVM(val *KubevirtIoApiCoreV1FeatureKVM) *NullableKubevirtIoApiCoreV1FeatureKVM {
	return &NullableKubevirtIoApiCoreV1FeatureKVM{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1FeatureKVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1FeatureKVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


