/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1VGPUOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1VGPUOptions{}

// KubevirtIoApiCoreV1VGPUOptions struct for KubevirtIoApiCoreV1VGPUOptions
type KubevirtIoApiCoreV1VGPUOptions struct {
	Display *KubevirtIoApiCoreV1VGPUDisplayOptions `json:"display,omitempty"`
}

// NewKubevirtIoApiCoreV1VGPUOptions instantiates a new KubevirtIoApiCoreV1VGPUOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1VGPUOptions() *KubevirtIoApiCoreV1VGPUOptions {
	this := KubevirtIoApiCoreV1VGPUOptions{}
	return &this
}

// NewKubevirtIoApiCoreV1VGPUOptionsWithDefaults instantiates a new KubevirtIoApiCoreV1VGPUOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1VGPUOptionsWithDefaults() *KubevirtIoApiCoreV1VGPUOptions {
	this := KubevirtIoApiCoreV1VGPUOptions{}
	return &this
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1VGPUOptions) GetDisplay() KubevirtIoApiCoreV1VGPUDisplayOptions {
	if o == nil || IsNil(o.Display) {
		var ret KubevirtIoApiCoreV1VGPUDisplayOptions
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1VGPUOptions) GetDisplayOk() (*KubevirtIoApiCoreV1VGPUDisplayOptions, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1VGPUOptions) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given KubevirtIoApiCoreV1VGPUDisplayOptions and assigns it to the Display field.
func (o *KubevirtIoApiCoreV1VGPUOptions) SetDisplay(v KubevirtIoApiCoreV1VGPUDisplayOptions) {
	o.Display = &v
}

func (o KubevirtIoApiCoreV1VGPUOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1VGPUOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1VGPUOptions struct {
	value *KubevirtIoApiCoreV1VGPUOptions
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1VGPUOptions) Get() *KubevirtIoApiCoreV1VGPUOptions {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1VGPUOptions) Set(val *KubevirtIoApiCoreV1VGPUOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1VGPUOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1VGPUOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1VGPUOptions(val *KubevirtIoApiCoreV1VGPUOptions) *NullableKubevirtIoApiCoreV1VGPUOptions {
	return &NullableKubevirtIoApiCoreV1VGPUOptions{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1VGPUOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1VGPUOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


