/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HarvesterhciIoV1beta1VirtualMachineRestoreSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HarvesterhciIoV1beta1VirtualMachineRestoreSpec{}

// HarvesterhciIoV1beta1VirtualMachineRestoreSpec struct for HarvesterhciIoV1beta1VirtualMachineRestoreSpec
type HarvesterhciIoV1beta1VirtualMachineRestoreSpec struct {
	DeletionPolicy *string `json:"deletionPolicy,omitempty"`
	KeepMacAddress *bool `json:"keepMacAddress,omitempty"`
	NewVM *bool `json:"newVM,omitempty"`
	Target K8sIoV1TypedLocalObjectReference `json:"target"`
	VirtualMachineBackupName string `json:"virtualMachineBackupName"`
	VirtualMachineBackupNamespace string `json:"virtualMachineBackupNamespace"`
}

type _HarvesterhciIoV1beta1VirtualMachineRestoreSpec HarvesterhciIoV1beta1VirtualMachineRestoreSpec

// NewHarvesterhciIoV1beta1VirtualMachineRestoreSpec instantiates a new HarvesterhciIoV1beta1VirtualMachineRestoreSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHarvesterhciIoV1beta1VirtualMachineRestoreSpec(target K8sIoV1TypedLocalObjectReference, virtualMachineBackupName string, virtualMachineBackupNamespace string) *HarvesterhciIoV1beta1VirtualMachineRestoreSpec {
	this := HarvesterhciIoV1beta1VirtualMachineRestoreSpec{}
	this.Target = target
	this.VirtualMachineBackupName = virtualMachineBackupName
	this.VirtualMachineBackupNamespace = virtualMachineBackupNamespace
	return &this
}

// NewHarvesterhciIoV1beta1VirtualMachineRestoreSpecWithDefaults instantiates a new HarvesterhciIoV1beta1VirtualMachineRestoreSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHarvesterhciIoV1beta1VirtualMachineRestoreSpecWithDefaults() *HarvesterhciIoV1beta1VirtualMachineRestoreSpec {
	this := HarvesterhciIoV1beta1VirtualMachineRestoreSpec{}
	var target K8sIoV1TypedLocalObjectReference
	this.Target = target
	var virtualMachineBackupName string = ""
	this.VirtualMachineBackupName = virtualMachineBackupName
	var virtualMachineBackupNamespace string = ""
	this.VirtualMachineBackupNamespace = virtualMachineBackupNamespace
	return &this
}

// GetDeletionPolicy returns the DeletionPolicy field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetDeletionPolicy() string {
	if o == nil || IsNil(o.DeletionPolicy) {
		var ret string
		return ret
	}
	return *o.DeletionPolicy
}

// GetDeletionPolicyOk returns a tuple with the DeletionPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetDeletionPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.DeletionPolicy) {
		return nil, false
	}
	return o.DeletionPolicy, true
}

// HasDeletionPolicy returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) HasDeletionPolicy() bool {
	if o != nil && !IsNil(o.DeletionPolicy) {
		return true
	}

	return false
}

// SetDeletionPolicy gets a reference to the given string and assigns it to the DeletionPolicy field.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetDeletionPolicy(v string) {
	o.DeletionPolicy = &v
}

// GetKeepMacAddress returns the KeepMacAddress field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetKeepMacAddress() bool {
	if o == nil || IsNil(o.KeepMacAddress) {
		var ret bool
		return ret
	}
	return *o.KeepMacAddress
}

// GetKeepMacAddressOk returns a tuple with the KeepMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetKeepMacAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.KeepMacAddress) {
		return nil, false
	}
	return o.KeepMacAddress, true
}

// HasKeepMacAddress returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) HasKeepMacAddress() bool {
	if o != nil && !IsNil(o.KeepMacAddress) {
		return true
	}

	return false
}

// SetKeepMacAddress gets a reference to the given bool and assigns it to the KeepMacAddress field.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetKeepMacAddress(v bool) {
	o.KeepMacAddress = &v
}

// GetNewVM returns the NewVM field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetNewVM() bool {
	if o == nil || IsNil(o.NewVM) {
		var ret bool
		return ret
	}
	return *o.NewVM
}

// GetNewVMOk returns a tuple with the NewVM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetNewVMOk() (*bool, bool) {
	if o == nil || IsNil(o.NewVM) {
		return nil, false
	}
	return o.NewVM, true
}

// HasNewVM returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) HasNewVM() bool {
	if o != nil && !IsNil(o.NewVM) {
		return true
	}

	return false
}

// SetNewVM gets a reference to the given bool and assigns it to the NewVM field.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetNewVM(v bool) {
	o.NewVM = &v
}

// GetTarget returns the Target field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetTarget() K8sIoV1TypedLocalObjectReference {
	if o == nil {
		var ret K8sIoV1TypedLocalObjectReference
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetTargetOk() (*K8sIoV1TypedLocalObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetTarget(v K8sIoV1TypedLocalObjectReference) {
	o.Target = v
}

// GetVirtualMachineBackupName returns the VirtualMachineBackupName field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetVirtualMachineBackupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VirtualMachineBackupName
}

// GetVirtualMachineBackupNameOk returns a tuple with the VirtualMachineBackupName field value
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetVirtualMachineBackupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualMachineBackupName, true
}

// SetVirtualMachineBackupName sets field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetVirtualMachineBackupName(v string) {
	o.VirtualMachineBackupName = v
}

// GetVirtualMachineBackupNamespace returns the VirtualMachineBackupNamespace field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetVirtualMachineBackupNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VirtualMachineBackupNamespace
}

// GetVirtualMachineBackupNamespaceOk returns a tuple with the VirtualMachineBackupNamespace field value
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) GetVirtualMachineBackupNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualMachineBackupNamespace, true
}

// SetVirtualMachineBackupNamespace sets field value
func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) SetVirtualMachineBackupNamespace(v string) {
	o.VirtualMachineBackupNamespace = v
}

func (o HarvesterhciIoV1beta1VirtualMachineRestoreSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HarvesterhciIoV1beta1VirtualMachineRestoreSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletionPolicy) {
		toSerialize["deletionPolicy"] = o.DeletionPolicy
	}
	if !IsNil(o.KeepMacAddress) {
		toSerialize["keepMacAddress"] = o.KeepMacAddress
	}
	if !IsNil(o.NewVM) {
		toSerialize["newVM"] = o.NewVM
	}
	toSerialize["target"] = o.Target
	toSerialize["virtualMachineBackupName"] = o.VirtualMachineBackupName
	toSerialize["virtualMachineBackupNamespace"] = o.VirtualMachineBackupNamespace
	return toSerialize, nil
}

func (o *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target",
		"virtualMachineBackupName",
		"virtualMachineBackupNamespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHarvesterhciIoV1beta1VirtualMachineRestoreSpec := _HarvesterhciIoV1beta1VirtualMachineRestoreSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHarvesterhciIoV1beta1VirtualMachineRestoreSpec)

	if err != nil {
		return err
	}

	*o = HarvesterhciIoV1beta1VirtualMachineRestoreSpec(varHarvesterhciIoV1beta1VirtualMachineRestoreSpec)

	return err
}

type NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec struct {
	value *HarvesterhciIoV1beta1VirtualMachineRestoreSpec
	isSet bool
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) Get() *HarvesterhciIoV1beta1VirtualMachineRestoreSpec {
	return v.value
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) Set(val *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec(val *HarvesterhciIoV1beta1VirtualMachineRestoreSpec) *NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec {
	return &NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec{value: val, isSet: true}
}

func (v NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHarvesterhciIoV1beta1VirtualMachineRestoreSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


