/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KubevirtIoApiCoreV1AccessCredentialSecretSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1AccessCredentialSecretSource{}

// KubevirtIoApiCoreV1AccessCredentialSecretSource struct for KubevirtIoApiCoreV1AccessCredentialSecretSource
type KubevirtIoApiCoreV1AccessCredentialSecretSource struct {
	SecretName string `json:"secretName"`
}

type _KubevirtIoApiCoreV1AccessCredentialSecretSource KubevirtIoApiCoreV1AccessCredentialSecretSource

// NewKubevirtIoApiCoreV1AccessCredentialSecretSource instantiates a new KubevirtIoApiCoreV1AccessCredentialSecretSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1AccessCredentialSecretSource(secretName string) *KubevirtIoApiCoreV1AccessCredentialSecretSource {
	this := KubevirtIoApiCoreV1AccessCredentialSecretSource{}
	this.SecretName = secretName
	return &this
}

// NewKubevirtIoApiCoreV1AccessCredentialSecretSourceWithDefaults instantiates a new KubevirtIoApiCoreV1AccessCredentialSecretSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1AccessCredentialSecretSourceWithDefaults() *KubevirtIoApiCoreV1AccessCredentialSecretSource {
	this := KubevirtIoApiCoreV1AccessCredentialSecretSource{}
	var secretName string = ""
	this.SecretName = secretName
	return &this
}

// GetSecretName returns the SecretName field value
func (o *KubevirtIoApiCoreV1AccessCredentialSecretSource) GetSecretName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretName
}

// GetSecretNameOk returns a tuple with the SecretName field value
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1AccessCredentialSecretSource) GetSecretNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretName, true
}

// SetSecretName sets field value
func (o *KubevirtIoApiCoreV1AccessCredentialSecretSource) SetSecretName(v string) {
	o.SecretName = v
}

func (o KubevirtIoApiCoreV1AccessCredentialSecretSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1AccessCredentialSecretSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secretName"] = o.SecretName
	return toSerialize, nil
}

func (o *KubevirtIoApiCoreV1AccessCredentialSecretSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secretName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKubevirtIoApiCoreV1AccessCredentialSecretSource := _KubevirtIoApiCoreV1AccessCredentialSecretSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKubevirtIoApiCoreV1AccessCredentialSecretSource)

	if err != nil {
		return err
	}

	*o = KubevirtIoApiCoreV1AccessCredentialSecretSource(varKubevirtIoApiCoreV1AccessCredentialSecretSource)

	return err
}

type NullableKubevirtIoApiCoreV1AccessCredentialSecretSource struct {
	value *KubevirtIoApiCoreV1AccessCredentialSecretSource
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) Get() *KubevirtIoApiCoreV1AccessCredentialSecretSource {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) Set(val *KubevirtIoApiCoreV1AccessCredentialSecretSource) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1AccessCredentialSecretSource(val *KubevirtIoApiCoreV1AccessCredentialSecretSource) *NullableKubevirtIoApiCoreV1AccessCredentialSecretSource {
	return &NullableKubevirtIoApiCoreV1AccessCredentialSecretSource{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1AccessCredentialSecretSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


