/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1InitrdInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1InitrdInfo{}

// KubevirtIoApiCoreV1InitrdInfo InitrdInfo show info about the initrd file
type KubevirtIoApiCoreV1InitrdInfo struct {
	// Checksum is the checksum of the initrd file
	Checksum *int64 `json:"checksum,omitempty"`
}

// NewKubevirtIoApiCoreV1InitrdInfo instantiates a new KubevirtIoApiCoreV1InitrdInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1InitrdInfo() *KubevirtIoApiCoreV1InitrdInfo {
	this := KubevirtIoApiCoreV1InitrdInfo{}
	return &this
}

// NewKubevirtIoApiCoreV1InitrdInfoWithDefaults instantiates a new KubevirtIoApiCoreV1InitrdInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1InitrdInfoWithDefaults() *KubevirtIoApiCoreV1InitrdInfo {
	this := KubevirtIoApiCoreV1InitrdInfo{}
	return &this
}

// GetChecksum returns the Checksum field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1InitrdInfo) GetChecksum() int64 {
	if o == nil || IsNil(o.Checksum) {
		var ret int64
		return ret
	}
	return *o.Checksum
}

// GetChecksumOk returns a tuple with the Checksum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1InitrdInfo) GetChecksumOk() (*int64, bool) {
	if o == nil || IsNil(o.Checksum) {
		return nil, false
	}
	return o.Checksum, true
}

// HasChecksum returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1InitrdInfo) HasChecksum() bool {
	if o != nil && !IsNil(o.Checksum) {
		return true
	}

	return false
}

// SetChecksum gets a reference to the given int64 and assigns it to the Checksum field.
func (o *KubevirtIoApiCoreV1InitrdInfo) SetChecksum(v int64) {
	o.Checksum = &v
}

func (o KubevirtIoApiCoreV1InitrdInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1InitrdInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Checksum) {
		toSerialize["checksum"] = o.Checksum
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1InitrdInfo struct {
	value *KubevirtIoApiCoreV1InitrdInfo
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1InitrdInfo) Get() *KubevirtIoApiCoreV1InitrdInfo {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1InitrdInfo) Set(val *KubevirtIoApiCoreV1InitrdInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1InitrdInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1InitrdInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1InitrdInfo(val *KubevirtIoApiCoreV1InitrdInfo) *NullableKubevirtIoApiCoreV1InitrdInfo {
	return &NullableKubevirtIoApiCoreV1InitrdInfo{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1InitrdInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1InitrdInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


