/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1Realtime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1Realtime{}

// KubevirtIoApiCoreV1Realtime Realtime holds the tuning knobs specific for realtime workloads.
type KubevirtIoApiCoreV1Realtime struct {
	// Mask defines the vcpu mask expression that defines which vcpus are used for realtime. Format matches libvirt's expressions. Example: \"0-3,^1\",\"0,2,3\",\"2-3\"
	Mask *string `json:"mask,omitempty"`
}

// NewKubevirtIoApiCoreV1Realtime instantiates a new KubevirtIoApiCoreV1Realtime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1Realtime() *KubevirtIoApiCoreV1Realtime {
	this := KubevirtIoApiCoreV1Realtime{}
	return &this
}

// NewKubevirtIoApiCoreV1RealtimeWithDefaults instantiates a new KubevirtIoApiCoreV1Realtime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1RealtimeWithDefaults() *KubevirtIoApiCoreV1Realtime {
	this := KubevirtIoApiCoreV1Realtime{}
	return &this
}

// GetMask returns the Mask field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1Realtime) GetMask() string {
	if o == nil || IsNil(o.Mask) {
		var ret string
		return ret
	}
	return *o.Mask
}

// GetMaskOk returns a tuple with the Mask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1Realtime) GetMaskOk() (*string, bool) {
	if o == nil || IsNil(o.Mask) {
		return nil, false
	}
	return o.Mask, true
}

// HasMask returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1Realtime) HasMask() bool {
	if o != nil && !IsNil(o.Mask) {
		return true
	}

	return false
}

// SetMask gets a reference to the given string and assigns it to the Mask field.
func (o *KubevirtIoApiCoreV1Realtime) SetMask(v string) {
	o.Mask = &v
}

func (o KubevirtIoApiCoreV1Realtime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1Realtime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mask) {
		toSerialize["mask"] = o.Mask
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1Realtime struct {
	value *KubevirtIoApiCoreV1Realtime
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1Realtime) Get() *KubevirtIoApiCoreV1Realtime {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1Realtime) Set(val *KubevirtIoApiCoreV1Realtime) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1Realtime) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1Realtime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1Realtime(val *KubevirtIoApiCoreV1Realtime) *NullableKubevirtIoApiCoreV1Realtime {
	return &NullableKubevirtIoApiCoreV1Realtime{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1Realtime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1Realtime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


