/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp{}

// KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp struct for KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp
type KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp struct {
	Phase *string `json:"phase,omitempty"`
	PhaseTransitionTimestamp *string `json:"phaseTransitionTimestamp,omitempty"`
}

// NewKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp instantiates a new KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp() *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp {
	this := KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp{}
	var phaseTransitionTimestamp string = "{}"
	this.PhaseTransitionTimestamp = &phaseTransitionTimestamp
	return &this
}

// NewKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestampWithDefaults instantiates a new KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestampWithDefaults() *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp {
	this := KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp{}
	var phaseTransitionTimestamp string = "{}"
	this.PhaseTransitionTimestamp = &phaseTransitionTimestamp
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) SetPhase(v string) {
	o.Phase = &v
}

// GetPhaseTransitionTimestamp returns the PhaseTransitionTimestamp field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) GetPhaseTransitionTimestamp() string {
	if o == nil || IsNil(o.PhaseTransitionTimestamp) {
		var ret string
		return ret
	}
	return *o.PhaseTransitionTimestamp
}

// GetPhaseTransitionTimestampOk returns a tuple with the PhaseTransitionTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) GetPhaseTransitionTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.PhaseTransitionTimestamp) {
		return nil, false
	}
	return o.PhaseTransitionTimestamp, true
}

// HasPhaseTransitionTimestamp returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) HasPhaseTransitionTimestamp() bool {
	if o != nil && !IsNil(o.PhaseTransitionTimestamp) {
		return true
	}

	return false
}

// SetPhaseTransitionTimestamp gets a reference to the given string and assigns it to the PhaseTransitionTimestamp field.
func (o *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) SetPhaseTransitionTimestamp(v string) {
	o.PhaseTransitionTimestamp = &v
}

func (o KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.PhaseTransitionTimestamp) {
		toSerialize["phaseTransitionTimestamp"] = o.PhaseTransitionTimestamp
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp struct {
	value *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) Get() *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) Set(val *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp(val *KubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) *NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp {
	return &NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1VirtualMachineInstanceMigrationPhaseTransitionTimestamp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


