/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HarvesterhciIoV1beta1KeyPairStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HarvesterhciIoV1beta1KeyPairStatus{}

// HarvesterhciIoV1beta1KeyPairStatus struct for HarvesterhciIoV1beta1KeyPairStatus
type HarvesterhciIoV1beta1KeyPairStatus struct {
	Conditions []HarvesterhciIoV1beta1Condition `json:"conditions,omitempty"`
	FingerPrint *string `json:"fingerPrint,omitempty"`
}

// NewHarvesterhciIoV1beta1KeyPairStatus instantiates a new HarvesterhciIoV1beta1KeyPairStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHarvesterhciIoV1beta1KeyPairStatus() *HarvesterhciIoV1beta1KeyPairStatus {
	this := HarvesterhciIoV1beta1KeyPairStatus{}
	return &this
}

// NewHarvesterhciIoV1beta1KeyPairStatusWithDefaults instantiates a new HarvesterhciIoV1beta1KeyPairStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHarvesterhciIoV1beta1KeyPairStatusWithDefaults() *HarvesterhciIoV1beta1KeyPairStatus {
	this := HarvesterhciIoV1beta1KeyPairStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1KeyPairStatus) GetConditions() []HarvesterhciIoV1beta1Condition {
	if o == nil || IsNil(o.Conditions) {
		var ret []HarvesterhciIoV1beta1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1KeyPairStatus) GetConditionsOk() ([]HarvesterhciIoV1beta1Condition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1KeyPairStatus) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []HarvesterhciIoV1beta1Condition and assigns it to the Conditions field.
func (o *HarvesterhciIoV1beta1KeyPairStatus) SetConditions(v []HarvesterhciIoV1beta1Condition) {
	o.Conditions = v
}

// GetFingerPrint returns the FingerPrint field value if set, zero value otherwise.
func (o *HarvesterhciIoV1beta1KeyPairStatus) GetFingerPrint() string {
	if o == nil || IsNil(o.FingerPrint) {
		var ret string
		return ret
	}
	return *o.FingerPrint
}

// GetFingerPrintOk returns a tuple with the FingerPrint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarvesterhciIoV1beta1KeyPairStatus) GetFingerPrintOk() (*string, bool) {
	if o == nil || IsNil(o.FingerPrint) {
		return nil, false
	}
	return o.FingerPrint, true
}

// HasFingerPrint returns a boolean if a field has been set.
func (o *HarvesterhciIoV1beta1KeyPairStatus) HasFingerPrint() bool {
	if o != nil && !IsNil(o.FingerPrint) {
		return true
	}

	return false
}

// SetFingerPrint gets a reference to the given string and assigns it to the FingerPrint field.
func (o *HarvesterhciIoV1beta1KeyPairStatus) SetFingerPrint(v string) {
	o.FingerPrint = &v
}

func (o HarvesterhciIoV1beta1KeyPairStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HarvesterhciIoV1beta1KeyPairStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.FingerPrint) {
		toSerialize["fingerPrint"] = o.FingerPrint
	}
	return toSerialize, nil
}

type NullableHarvesterhciIoV1beta1KeyPairStatus struct {
	value *HarvesterhciIoV1beta1KeyPairStatus
	isSet bool
}

func (v NullableHarvesterhciIoV1beta1KeyPairStatus) Get() *HarvesterhciIoV1beta1KeyPairStatus {
	return v.value
}

func (v *NullableHarvesterhciIoV1beta1KeyPairStatus) Set(val *HarvesterhciIoV1beta1KeyPairStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableHarvesterhciIoV1beta1KeyPairStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHarvesterhciIoV1beta1KeyPairStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHarvesterhciIoV1beta1KeyPairStatus(val *HarvesterhciIoV1beta1KeyPairStatus) *NullableHarvesterhciIoV1beta1KeyPairStatus {
	return &NullableHarvesterhciIoV1beta1KeyPairStatus{value: val, isSet: true}
}

func (v NullableHarvesterhciIoV1beta1KeyPairStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHarvesterhciIoV1beta1KeyPairStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


