/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the K8sIoV1ObjectFieldSelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &K8sIoV1ObjectFieldSelector{}

// K8sIoV1ObjectFieldSelector struct for K8sIoV1ObjectFieldSelector
type K8sIoV1ObjectFieldSelector struct {
	ApiVersion *string `json:"apiVersion,omitempty"`
	FieldPath string `json:"fieldPath"`
}

type _K8sIoV1ObjectFieldSelector K8sIoV1ObjectFieldSelector

// NewK8sIoV1ObjectFieldSelector instantiates a new K8sIoV1ObjectFieldSelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewK8sIoV1ObjectFieldSelector(fieldPath string) *K8sIoV1ObjectFieldSelector {
	this := K8sIoV1ObjectFieldSelector{}
	this.FieldPath = fieldPath
	return &this
}

// NewK8sIoV1ObjectFieldSelectorWithDefaults instantiates a new K8sIoV1ObjectFieldSelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewK8sIoV1ObjectFieldSelectorWithDefaults() *K8sIoV1ObjectFieldSelector {
	this := K8sIoV1ObjectFieldSelector{}
	var fieldPath string = ""
	this.FieldPath = fieldPath
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *K8sIoV1ObjectFieldSelector) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *K8sIoV1ObjectFieldSelector) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *K8sIoV1ObjectFieldSelector) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *K8sIoV1ObjectFieldSelector) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetFieldPath returns the FieldPath field value
func (o *K8sIoV1ObjectFieldSelector) GetFieldPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldPath
}

// GetFieldPathOk returns a tuple with the FieldPath field value
// and a boolean to check if the value has been set.
func (o *K8sIoV1ObjectFieldSelector) GetFieldPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldPath, true
}

// SetFieldPath sets field value
func (o *K8sIoV1ObjectFieldSelector) SetFieldPath(v string) {
	o.FieldPath = v
}

func (o K8sIoV1ObjectFieldSelector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o K8sIoV1ObjectFieldSelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	toSerialize["fieldPath"] = o.FieldPath
	return toSerialize, nil
}

func (o *K8sIoV1ObjectFieldSelector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fieldPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varK8sIoV1ObjectFieldSelector := _K8sIoV1ObjectFieldSelector{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varK8sIoV1ObjectFieldSelector)

	if err != nil {
		return err
	}

	*o = K8sIoV1ObjectFieldSelector(varK8sIoV1ObjectFieldSelector)

	return err
}

type NullableK8sIoV1ObjectFieldSelector struct {
	value *K8sIoV1ObjectFieldSelector
	isSet bool
}

func (v NullableK8sIoV1ObjectFieldSelector) Get() *K8sIoV1ObjectFieldSelector {
	return v.value
}

func (v *NullableK8sIoV1ObjectFieldSelector) Set(val *K8sIoV1ObjectFieldSelector) {
	v.value = val
	v.isSet = true
}

func (v NullableK8sIoV1ObjectFieldSelector) IsSet() bool {
	return v.isSet
}

func (v *NullableK8sIoV1ObjectFieldSelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableK8sIoV1ObjectFieldSelector(val *K8sIoV1ObjectFieldSelector) *NullableK8sIoV1ObjectFieldSelector {
	return &NullableK8sIoV1ObjectFieldSelector{value: val, isSet: true}
}

func (v NullableK8sIoV1ObjectFieldSelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableK8sIoV1ObjectFieldSelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


