/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NetworkHarvesterhciIoV1beta1ClusterNetworkStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkHarvesterhciIoV1beta1ClusterNetworkStatus{}

// NetworkHarvesterhciIoV1beta1ClusterNetworkStatus struct for NetworkHarvesterhciIoV1beta1ClusterNetworkStatus
type NetworkHarvesterhciIoV1beta1ClusterNetworkStatus struct {
	Conditions []NetworkHarvesterhciIoV1beta1Condition `json:"conditions,omitempty"`
}

// NewNetworkHarvesterhciIoV1beta1ClusterNetworkStatus instantiates a new NetworkHarvesterhciIoV1beta1ClusterNetworkStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkHarvesterhciIoV1beta1ClusterNetworkStatus() *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus {
	this := NetworkHarvesterhciIoV1beta1ClusterNetworkStatus{}
	return &this
}

// NewNetworkHarvesterhciIoV1beta1ClusterNetworkStatusWithDefaults instantiates a new NetworkHarvesterhciIoV1beta1ClusterNetworkStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkHarvesterhciIoV1beta1ClusterNetworkStatusWithDefaults() *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus {
	this := NetworkHarvesterhciIoV1beta1ClusterNetworkStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) GetConditions() []NetworkHarvesterhciIoV1beta1Condition {
	if o == nil || IsNil(o.Conditions) {
		var ret []NetworkHarvesterhciIoV1beta1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) GetConditionsOk() ([]NetworkHarvesterhciIoV1beta1Condition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []NetworkHarvesterhciIoV1beta1Condition and assigns it to the Conditions field.
func (o *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) SetConditions(v []NetworkHarvesterhciIoV1beta1Condition) {
	o.Conditions = v
}

func (o NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	return toSerialize, nil
}

type NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus struct {
	value *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus
	isSet bool
}

func (v NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) Get() *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus {
	return v.value
}

func (v *NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) Set(val *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus(val *NetworkHarvesterhciIoV1beta1ClusterNetworkStatus) *NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus {
	return &NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus{value: val, isSet: true}
}

func (v NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkHarvesterhciIoV1beta1ClusterNetworkStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


