/*
Harvester APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harvester

import (
	"encoding/json"
)

// checks if the KubevirtIoApiCoreV1SEVPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubevirtIoApiCoreV1SEVPolicy{}

// KubevirtIoApiCoreV1SEVPolicy struct for KubevirtIoApiCoreV1SEVPolicy
type KubevirtIoApiCoreV1SEVPolicy struct {
	EncryptedState *bool `json:"encryptedState,omitempty"`
}

// NewKubevirtIoApiCoreV1SEVPolicy instantiates a new KubevirtIoApiCoreV1SEVPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubevirtIoApiCoreV1SEVPolicy() *KubevirtIoApiCoreV1SEVPolicy {
	this := KubevirtIoApiCoreV1SEVPolicy{}
	return &this
}

// NewKubevirtIoApiCoreV1SEVPolicyWithDefaults instantiates a new KubevirtIoApiCoreV1SEVPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubevirtIoApiCoreV1SEVPolicyWithDefaults() *KubevirtIoApiCoreV1SEVPolicy {
	this := KubevirtIoApiCoreV1SEVPolicy{}
	return &this
}

// GetEncryptedState returns the EncryptedState field value if set, zero value otherwise.
func (o *KubevirtIoApiCoreV1SEVPolicy) GetEncryptedState() bool {
	if o == nil || IsNil(o.EncryptedState) {
		var ret bool
		return ret
	}
	return *o.EncryptedState
}

// GetEncryptedStateOk returns a tuple with the EncryptedState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubevirtIoApiCoreV1SEVPolicy) GetEncryptedStateOk() (*bool, bool) {
	if o == nil || IsNil(o.EncryptedState) {
		return nil, false
	}
	return o.EncryptedState, true
}

// HasEncryptedState returns a boolean if a field has been set.
func (o *KubevirtIoApiCoreV1SEVPolicy) HasEncryptedState() bool {
	if o != nil && !IsNil(o.EncryptedState) {
		return true
	}

	return false
}

// SetEncryptedState gets a reference to the given bool and assigns it to the EncryptedState field.
func (o *KubevirtIoApiCoreV1SEVPolicy) SetEncryptedState(v bool) {
	o.EncryptedState = &v
}

func (o KubevirtIoApiCoreV1SEVPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubevirtIoApiCoreV1SEVPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EncryptedState) {
		toSerialize["encryptedState"] = o.EncryptedState
	}
	return toSerialize, nil
}

type NullableKubevirtIoApiCoreV1SEVPolicy struct {
	value *KubevirtIoApiCoreV1SEVPolicy
	isSet bool
}

func (v NullableKubevirtIoApiCoreV1SEVPolicy) Get() *KubevirtIoApiCoreV1SEVPolicy {
	return v.value
}

func (v *NullableKubevirtIoApiCoreV1SEVPolicy) Set(val *KubevirtIoApiCoreV1SEVPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableKubevirtIoApiCoreV1SEVPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableKubevirtIoApiCoreV1SEVPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubevirtIoApiCoreV1SEVPolicy(val *KubevirtIoApiCoreV1SEVPolicy) *NullableKubevirtIoApiCoreV1SEVPolicy {
	return &NullableKubevirtIoApiCoreV1SEVPolicy{value: val, isSet: true}
}

func (v NullableKubevirtIoApiCoreV1SEVPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubevirtIoApiCoreV1SEVPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


